"""
escalation/drafter.py — Forensic dossier payload builder for authority escalation.

Purpose:
  Builds the email / webhook payload from a completed forensic dossier.
  Nothing is sent here — this module only DRAFTS the payload.
  Actual dispatch requires human confirmation via send_bridge.py.

Rationale (§7):
  India's National Cyber Crime Portal has NO public API for third-party
  auto-submission. Auto-DRAFTED, human-CONFIRMED is both the legally honest
  framing and the better live-demo beat.

Output formats:
  - email: formatted text body + PDF attachment reference
  - slack/discord webhook: JSON payload with key summary fields
  - generic webhook: JSON payload for any configured endpoint
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, TypedDict

logger = logging.getLogger(__name__)


class EscalationPayload(TypedDict):
    format: str                   # "email" | "slack" | "discord" | "webhook"
    destination: str              # Email address or webhook URL
    subject: str
    body_text: str                # Plain text version
    body_html: Optional[str]      # HTML version for email
    json_payload: Optional[dict]  # For webhook/slack/discord
    pdf_filename: str             # PDF will be attached by send_bridge.py
    drafted_at: str               # ISO timestamp
    call_id: str
    verdict: str


def draft_email_payload(
    call_id: str,
    verdict: str,
    identifiers: Dict[str, Any],
    hash_result: Dict[str, Any],
    factcheck_history: List[Dict[str, Any]],
    destination_email: str,
    pdf_filename: str,
) -> EscalationPayload:
    """
    Draft an email payload for a cybercrime cell escalation.

    Parameters match fields from the ForensicDossier / CallSession.
    """
    now = datetime.now(timezone.utc).isoformat()
    upi_ids = ", ".join(identifiers.get("upi_ids", [])) or "None detected"
    phones = ", ".join(identifiers.get("phone_numbers", [])) or "None detected"
    entities = ", ".join(identifiers.get("impersonated_entities", [])) or "None"

    subject = f"[PhaseGuard] Cyber Crime Report — Call {call_id} — Verdict: {verdict}"

    body_text = f"""PhaseGuard Anti-Scam System — Automated Forensic Report
=============================================================

Call ID: {call_id}
Analysis Verdict: {verdict}
Generated: {now}

IMPORTANT: This report was drafted automatically by PhaseGuard and sent ONLY
after explicit human confirmation by the call recipient.

KEY EVIDENCE:
  - UPI IDs mentioned: {upi_ids}
  - Phone numbers mentioned: {phones}
  - Impersonated entities: {entities}
  - Audio SHA-256: {hash_result.get('sha256_hex', 'N/A')}
  - Audio duration: {hash_result.get('duration_seconds', 0):.1f} seconds

FACT-CHECK VERDICTS: {len(factcheck_history)} verdicts recorded during call.
  Final status: {factcheck_history[-1].get('status', 'N/A') if factcheck_history else 'N/A'}

A complete forensic PDF dossier (including spectrogram, full transcript, and
DSP analysis) is attached to this email.

To file an official complaint:
  - National Cyber Crime Portal: https://cybercrime.gov.in
  - Helpline: 1930

This report was generated by PhaseGuard Anti-Scam OS.
"""

    body_html = f"""
<html><body>
<h2 style="color:#c0392b;">🛡 PhaseGuard — Cyber Crime Report</h2>
<p><strong>Call ID:</strong> {call_id}</p>
<p><strong>Verdict:</strong> <span style="color:{'red' if verdict=='CRITICAL' else 'orange'};font-weight:bold;">{verdict}</span></p>
<p><strong>Generated:</strong> {now}</p>
<hr>
<h3>Key Evidence</h3>
<ul>
  <li><strong>UPI IDs:</strong> {upi_ids}</li>
  <li><strong>Phone numbers:</strong> {phones}</li>
  <li><strong>Impersonated entities:</strong> {entities}</li>
  <li><strong>Audio SHA-256:</strong> <code>{hash_result.get('sha256_hex', 'N/A')}</code></li>
</ul>
<p>See attached PDF for full forensic dossier.</p>
<hr>
<p><small>To report: <a href="https://cybercrime.gov.in">cybercrime.gov.in</a> | 1930</small></p>
</body></html>
"""

    return EscalationPayload(
        format="email",
        destination=destination_email,
        subject=subject,
        body_text=body_text,
        body_html=body_html,
        json_payload=None,
        pdf_filename=pdf_filename,
        drafted_at=now,
        call_id=call_id,
        verdict=verdict,
    )


def draft_webhook_payload(
    call_id: str,
    verdict: str,
    identifiers: Dict[str, Any],
    hash_result: Dict[str, Any],
    webhook_url: str,
    pdf_filename: str,
    format: str = "slack",
) -> EscalationPayload:
    """
    Draft a Slack / Discord / generic webhook payload.

    format: "slack" | "discord" | "webhook"
    """
    now = datetime.now(timezone.utc).isoformat()
    color = {"CRITICAL": "#c0392b", "SAFE": "#27ae60", "UNCERTAIN": "#f39c12"}.get(
        verdict, "#7f8c8d"
    )

    if format in ("slack", "discord"):
        # Slack Block Kit / Discord Embed format
        json_payload = {
            "username": "PhaseGuard",
            "content": f"⚠ **Cyber Crime Alert** — Call `{call_id}` — Verdict: **{verdict}**",
            "embeds": [
                {
                    "title": f"PhaseGuard Forensic Report — {call_id}",
                    "color": int(color.lstrip("#"), 16),
                    "fields": [
                        {"name": "Verdict", "value": verdict, "inline": True},
                        {"name": "Call ID", "value": call_id, "inline": True},
                        {
                            "name": "UPI IDs",
                            "value": ", ".join(identifiers.get("upi_ids", [])) or "None",
                            "inline": False,
                        },
                        {
                            "name": "Phones",
                            "value": ", ".join(identifiers.get("phone_numbers", [])) or "None",
                            "inline": False,
                        },
                        {
                            "name": "Audio Hash",
                            "value": f"`{hash_result.get('sha256_hex', 'N/A')[:16]}...`",
                            "inline": False,
                        },
                    ],
                    "footer": {"text": "PhaseGuard Anti-Scam OS | cybercrime.gov.in | 1930"},
                    "timestamp": now,
                }
            ],
        }
    else:
        json_payload = {
            "call_id": call_id,
            "verdict": verdict,
            "identifiers": identifiers,
            "sha256": hash_result.get("sha256_hex", ""),
            "pdf_filename": pdf_filename,
            "drafted_at": now,
        }

    return EscalationPayload(
        format=format,
        destination=webhook_url,
        subject=f"PhaseGuard Alert — {call_id} — {verdict}",
        body_text=f"PhaseGuard alert for call {call_id}: {verdict}",
        body_html=None,
        json_payload=json_payload,
        pdf_filename=pdf_filename,
        drafted_at=now,
        call_id=call_id,
        verdict=verdict,
    )
